In [1]:
import numpy as np

In [2]:
# 1D Array 

In [3]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [4]:
a.shape

(6,)

In [5]:
#2D Array 
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
b.shape

(4, 3)

In [7]:
# 3D array
c = np.arange(24).reshape(4,3,2)

In [8]:
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [9]:
c.shape

(4, 3, 2)

In [10]:
#Arithematic Operation using Numpy
mat1 = np.array([10,10,10])
mat2 = np.array([5,5,5])

In [11]:
mat1 + mat2 #ADDITION

array([15, 15, 15])

In [12]:
mat1 - mat2 # SUBTRACTION

array([5, 5, 5])

In [13]:
mat1*mat2 # Multiplication

array([50, 50, 50])

In [14]:
mat1/mat2 #Division

array([2., 2., 2.])

In [ ]:
#Comparision Operators in numpy

In [15]:
a < 25

array([ True,  True,  True,  True,  True,  True])

In [16]:
b < 25 

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [17]:
b<12

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [19]:
b < 9

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [20]:
a *= 3

In [21]:
print(a)

[ 0  3  6  9 12 15]


In [22]:
b+=3
print(b)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [23]:
mat1 += mat2
print(mat1)

[15 15 15]


In [ ]:
#Unary Operations in Numpy

In [24]:
ages = np.array([12,15,20,40,30,8,18])

In [25]:
ages.min()

8

In [26]:
ages.max()

40

In [27]:
ages.sum()

143

In [ ]:
# Axes Based calculations in NUMPY
 Axis 1 = Cols
 Axis 2 = Rows

In [28]:
number = np.arange(12).reshape(4,3)
print(number)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
number.sum(axis = 0)

array([18, 22, 26])

In [30]:
number.sum(axis = 1)

array([ 3, 12, 21, 30])

In [31]:
number.min(axis = 0)

array([0, 1, 2])

In [32]:
number.min(axis = 1)

array([0, 3, 6, 9])

In [33]:
number.max(axis = 1)

array([ 2,  5,  8, 11])

In [35]:
number.max(axis = 0)

array([ 9, 10, 11])